package main

import (
	"log"

	generator "github.com/tuanhuu3264/tuan-invoice"
)

func main() {
	// Create options
	options := &generator.Options{
		TextInvoiceTitle:       "INVOICE",
		TextRefTitle:           "Ref",
		TextDateTitle:          "Date",
		TextVersionTitle:       "Version",
		TextItemsNameTitle:     "Item",
		TextItemsUnitCostTitle: "Unit Price",
		TextItemsQuantityTitle: "Qty",
		TextItemsTotalHTTitle:  "Total HT",
		TextItemsTaxTitle:      "Tax",
		TextItemsDiscountTitle: "Discount",
		TextItemsTotalTTCTitle: "Total TTC",
		TextTotalTotal:         "TOTAL HT",
		TextTotalTax:           "TOTAL TAX",
		TextTotalWithTax:       "TOTAL TTC",
		TextTotalDiscounted:    "DISCOUNT",
		TextPaymentTermTitle:   "Payment Term",
		Font:                   "Arial",
		BoldFont:               "Arial",
		BaseTextColor:          []int{35, 35, 35},
		GreyTextColor:          []int{128, 128, 128},
		GreyBgColor:            []int{240, 240, 240},
		DarkBgColor:            []int{0, 0, 0},
	}

	// Create multi-document
	md := generator.NewMultiDocument(options)

	// Set header
	header := &generator.HeaderFooter{
		Text:     "Multi-Document Invoice Generator",
		FontSize: 10,
	}
	md.SetHeader(header)

	// Set footer
	footer := &generator.HeaderFooter{
		Text:     "Generated by Multi-Document System",
		FontSize: 8,
	}
	md.SetFooter(footer)

	// Create first document
	doc1, err := generator.New(generator.Invoice, options)
	if err != nil {
		log.Fatal(err)
	}
	doc1.SetRef("INV-001")
	doc1.SetVersion("1.0")
	doc1.SetDate("15/01/2024")
	doc1.SetDescription("First invoice description")
	doc1.SetPaymentTerm("30 days")

	// Set company info
	doc1.Company = &generator.Contact{
		Name: "Company A",
		Address: &generator.Address{
			Address:    "123 Main St",
			City:       "City",
			PostalCode: "12345",
			Country:    "Country",
		},
	}

	// Set customer info
	doc1.Customer = &generator.Contact{
		Name: "Customer A",
		Address: &generator.Address{
			Address:    "456 Oak Ave",
			City:       "Town",
			PostalCode: "67890",
			Country:    "Country",
		},
	}

	// Add items
	doc1.AppendItem(&generator.Item{
		Name:     "Item 1",
		UnitCost: "100.0",
		Quantity: "2",
		Tax:      &generator.Tax{Percent: "10"},
	})

	// Create second document
	doc2, err := generator.New(generator.Invoice, options)
	if err != nil {
		log.Fatal(err)
	}
	doc2.SetRef("INV-002")
	doc2.SetVersion("1.0")
	doc2.SetDate("16/01/2024")
	doc2.SetDescription("Second invoice description")
	doc2.SetPaymentTerm("15 days")

	// Set company info
	doc2.Company = &generator.Contact{
		Name: "Company B",
		Address: &generator.Address{
			Address:    "789 Pine Rd",
			City:       "Village",
			PostalCode: "11111",
			Country:    "Country",
		},
	}

	// Set customer info
	doc2.Customer = &generator.Contact{
		Name: "Customer B",
		Address: &generator.Address{
			Address:    "321 Elm St",
			City:       "City",
			PostalCode: "22222",
			Country:    "Country",
		},
	}

	// Add items
	doc2.AppendItem(&generator.Item{
		Name:     "Item 2",
		UnitCost: "150.0",
		Quantity: "1",
		Tax:      &generator.Tax{Percent: "15"},
	})

	// Add documents to multi-document
	md.AddDocument(doc1)
	md.AddDocument(doc2)

	// Build PDF
	pdf, err := md.Build()
	if err != nil {
		log.Fatal(err)
	}

	// Save to file
	err = pdf.OutputFileAndClose("multi_document_example.pdf")
	if err != nil {
		log.Fatal(err)
	}

	log.Println("Multi-document PDF generated successfully!")
}
